# SET DEFAULT SIMD FLAGS
if(CMAKE_SYSTEM_PROCESSOR MATCHES "(amd64.*)|(x86_64.*)|(AMD64.*)|(i686.*)|(i386.*)|(x86.*)|(AMD64)")
  if(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    if(WIN32)
      add_compile_options(-mavx2)
    else()
      add_compile_options(-mavx2)
    endif()
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    if(WIN32)
      add_compile_options(-mavx2)
    else()
      add_compile_options(-mavx2)
    endif()
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" AND MSVC_VERSION GREATER 1900)
      add_compile_options(/arch:AVX2)
  else()
     MESSAGE(INFO "simd not set for '${CMAKE_CXX_COMPILER_ID}' compiler.")
  endif()
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64.*|AARCH64.*|arm64.*|ARM64.*|arm.*|ARM.*)")
    if(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    if(WIN32)
      add_compile_options(-mfpu=neon)
    else()
      add_compile_options(-mfpu=neon)
    endif()
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    if(WIN32)
      add_compile_options(-mfpu=neon)
    else()
      add_compile_options(-mfpu=neon)
    endif()
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" AND MSVC_VERSION GREATER 1900)
    # add_compile_options(/arch:AVX2) #AUTODETECT ?
  else()
    MESSAGE(INFO "simd not set for '${CMAKE_CXX_COMPILER_ID}' compiler.")
    endif()
endif()

