# SET DEFAULT SIMD FLAGS
if(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
  if(WIN32)
    MESSAGE(FATAl_ERROR "WIN32 CLANG not handle yet")
  else()
        add_compile_options(-mavx2)
  endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  if(WIN32)
    MESSAGE(FATAl_ERROR "WIN32 GCC not handle yet")
  else()
    add_compile_options(-mavx2)
  endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" AND MSVC_VERSION GREATER 1900)
    add_compile_options(/arch:AVX2)
else()
    MESSAGE(FATAl_ERROR "simd not set set for '${CMAKE_CXX_COMPILER_ID}' compiler.")
endif()